//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace b2yweb_mvc4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUsuario
    {
        public GUsuario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public short cd_gusuario { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
